---
# Main tasks file for kubernetes_worker role

- name: Add Kubernetes signing key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /tmp/kubernetes-apt-key.gpg
  become: yes
  when: ansible_os_family == "Debian"

- name: Dearmor key
  shell: cat /tmp/kubernetes-apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: yes
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: ansible_os_family == "Debian"

- name: Create kubernetes repository directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: yes
  when: ansible_os_family == "Debian"

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    state: present
    filename: kubernetes
  become: yes
  when: ansible_os_family == "Debian"

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  when: ansible_os_family == "Debian"

- name: Install containerd
  apt:
    name: containerd
    state: present
  become: yes
  when: ansible_os_family == "Debian"

- name: Create containerd directory
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  become: yes

- name: Configure containerd
  shell: containerd config default > /etc/containerd/config.toml
  become: yes
  args:
    creates: /etc/containerd/config.toml

- name: Edit containerd configuration to use systemd cgroup driver
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^\s+SystemdCgroup = false'
    line: '            SystemdCgroup = true'
  become: yes
  notify: restart containerd

- name: Install Kubernetes packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - lsof
  when: ansible_os_family == "Debian"

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - containerd
  become: yes
  when: ansible_os_family == "Debian"

- name: Disable swap
  command: swapoff -a
  become: yes

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '.*swap.*'
    state: absent
  become: yes

- name: Enable kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter
  become: yes

- name: Add kernel modules to /etc/modules-load.d/
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/kubernetes.conf
    mode: '0644'
  become: yes

- name: Configure sysctl for Kubernetes
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: '0644'
  become: yes

- name: Apply sysctl changes immediately
  command: sysctl --system
  become: yes