---
# Main tasks file for base_server role

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true
  when: ansible_os_family == "Debian"

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
  become: true
  when: ansible_os_family == "Debian"

- name: Ensure git is not installed
  ansible.builtin.package:
    name: git
    state: absent
  become: true

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - htop
    - git
    - curl
    - wget
    - unzip
    - ca-certificates
    - gnupg
    - lsb-release
    - ntp
    - sudo

- name: Set timezone
  community.general.timezone:
    name: "{{ server_timezone }}"
  become: true

- name: Check if NTP service exists (ntpsec)
  ansible.builtin.stat:
    path: /lib/systemd/system/ntpsec.service
  register: ntpsec_exists
  become: true

- name: Check if NTP service exists (ntp)
  ansible.builtin.stat:
    path: /lib/systemd/system/ntp.service
  register: ntp_exists
  become: true

- name: Ensure NTP service is running (ntpsec)
  ansible.builtin.service:
    name: ntpsec
    state: started
    enabled: true
  become: true
  when: ntpsec_exists.stat.exists

- name: Ensure NTP service is running (ntp)
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true
  become: true
  when: ntp_exists.stat.exists

- name: Configure SSH for security
  ansible.builtin.template:
    src: ssh_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart ssh

- name: Create a strong password policy
  ansible.builtin.copy:
    src: pwquality.conf
    dest: /etc/security/pwquality.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  when: ansible_os_family == "Debian"
