---
# Inventory file for server management

all:
  children:
    base_servers:
      hosts:
        server1:
          ansible_host: 192.168.1.101
        server2:
          ansible_host: 192.168.1.102
    
    jenkins_servers:
      hosts:
        jenkins-server:
          ansible_host: jenkins-server.i.psilva.org
          ansible_user: ubuntu
          jenkins_http_port: 8080
          jenkins_agent_port: 50000
          server_timezone: "UTC"
    # Add more server groups as needed
