---
# Inventory file for server management

all:
  children:
    production:
      children:
        jenkins_servers:
          hosts:
            jenkins-server:
              ansible_host: jenkins-server.i.psilva.org
              ansible_user: ubuntu
              server_timezone: "UTC"
        # Add more server groups as needed
