---
# Main Kubernetes deployment playbook
- name: Deploy Kubernetes Master
  hosts: kubernetes_master_nodes
  gather_facts: true
  vars:
    apiserver_advertise_address: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    pod_network_cidr: "10.244.0.0/16"
    service_cidr: "10.96.0.0/12"
    network_plugin: "calico"
    calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/calico.yaml"
  roles:
    - role: ../../roles/kubernetes_master
