---
# Tasks for mounting virtfs shared directory

- name: Ensure the mount point directory exists
  ansible.builtin.file:
    path: "/mnt/{{ inventory_hostname.split('.')[0] }}"
    state: directory
    mode: "0755"
  become: true

- name: Check if mount tag exists
  ansible.builtin.shell: cat /proc/mounts | grep -q "{{ virtfs_mount_tag }}"
  register: mount_exists
  failed_when: false
  changed_when: false
  become: true

- name: Mount the virtfs shared directory
  ansible.posix.mount:
    path: "/mnt/{{ inventory_hostname.split('.')[0] }}"
    src: "{{ virtfs_mount_tag }}"
    fstype: 9p
    opts: "trans=virtio,version=9p2000.L,rw"
    state: mounted
  when: mount_exists.rc != 0
  become: true

- name: Ensure mount persists on reboot by adding to fstab
  ansible.posix.mount:
    path: "/mnt/{{ inventory_hostname.split('.')[0] }}"
    src: "{{ virtfs_mount_tag }}"
    fstype: 9p
    opts: "trans=virtio,version=9p2000.L,rw"
    state: present
  become: true
