---
# Tasks for mounting virtfs shared directory

- name: Ensure the mount point directory exists
  file:
    path: "/mnt/{{ inventory_hostname.split('.')[0] }}"
    state: directory
    mode: '0755'
  become: yes

- name: Check if mount tag exists
  shell: cat /proc/mounts | grep -q "{{ virtfs_mount_tag }}"
  register: mount_exists
  failed_when: false
  changed_when: false
  become: yes

- name: Mount the virtfs shared directory
  mount:
    path: "/mnt/{{ inventory_hostname.split('.')[0] }}"
    src: "{{ virtfs_mount_tag }}"
    fstype: 9p
    opts: "trans=virtio,version=9p2000.L,rw"
    state: mounted
  when: mount_exists.rc != 0
  become: yes

- name: Ensure mount persists on reboot by adding to fstab
  mount:
    path: "/mnt/{{ inventory_hostname.split('.')[0] }}"
    src: "{{ virtfs_mount_tag }}"
    fstype: 9p
    opts: "trans=virtio,version=9p2000.L,rw"
    state: present
  become: yes 