---
# Jenkins Server Playbook
# This playbook applies the base_server role for system configuration and jenkins_podman role to deploy Jenkins

- name: Deploy Jenkins Server
  hosts: jenkins_server
  become: true
  gather_facts: true

  roles:
    - role: ../../roles/base_server
    - role: ../../roles/virtfs_mount
    - role: ../../roles/jenkins_podman

  post_tasks:
    - name: Report completion
      ansible.builtin.debug:
        msg: "Jenkins server configuration completed successfully on {{ inventory_hostname }}"

    - name: Show Jenkins access information
      ansible.builtin.debug:
        msg: "Jenkins is available at http://{{ inventory_hostname }}:{{ jenkins_http_port }}"
