---
# Handlers for jenkins_podman role

- name: Reload user systemd
  shell: XDG_RUNTIME_DIR=/run/user/$(id -u) systemctl --user daemon-reload
  become: yes
  become_user: "{{ systemd_user }}"
  
- name: Restart Jenkins container
  systemd:
    name: jenkins.service
    state: restarted
    scope: user
  become: yes
  become_user: "{{ systemd_user }}" 