---
# Test tasks for verifying Kubernetes cluster and Calico functionality

- name: Verify Kubernetes cluster nodes status
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl get nodes -o wide
  register: nodes_status
  become: yes
  changed_when: false

- name: Display nodes status
  debug:
    var: nodes_status.stdout_lines

- name: Verify Calico pods are running
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl get pods -n kube-system -l k8s-app=calico-node -o wide
  register: calico_pods
  become: yes
  changed_when: false

- name: Display Calico pods status
  debug:
    var: calico_pods.stdout_lines

- name: Verify Calico version
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl get pods -n kube-system -l k8s-app=calico-node -o jsonpath='{.items[0].spec.containers[0].image}'
  register: calico_version
  become: yes
  changed_when: false

- name: Display Calico version
  debug:
    var: calico_version.stdout

- name: Check CNI configuration
  shell: |
    ls -la /etc/cni/net.d/
  register: cni_config
  become: yes
  changed_when: false

- name: Display CNI configuration
  debug:
    var: cni_config.stdout_lines

- name: Create test namespace
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl create namespace calico-test
  register: create_namespace
  become: yes
  changed_when: false
  failed_when: create_namespace.rc != 0 and "AlreadyExists" not in create_namespace.stderr

- name: Create test pod to verify connectivity
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: pingtest
      namespace: calico-test
    spec:
      containers:
      - name: pingtest
        image: alpine
        command:
          - sleep
          - "3600"
      restartPolicy: Always
    EOF
  register: create_pod
  become: yes
  changed_when: false

- name: Wait for test pod to be running
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl wait --namespace=calico-test --for=condition=ready pod/pingtest --timeout=60s
  register: pod_ready
  become: yes
  changed_when: false
  ignore_errors: true

- name: Get pod IP address
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl get pod pingtest -n calico-test -o jsonpath='{.status.podIP}'
  register: pod_ip
  become: yes
  changed_when: false
  when: pod_ready is succeeded

- name: Display pod IP
  debug:
    var: pod_ip.stdout
  when: pod_ready is succeeded and pod_ip is defined

- name: Test DNS resolution from pod
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl exec -n calico-test pingtest -- nslookup kubernetes.default.svc.cluster.local
  register: dns_test
  become: yes
  changed_when: false
  ignore_errors: true
  when: pod_ready is succeeded

- name: Display DNS test results
  debug:
    var: dns_test.stdout_lines
  when: dns_test is defined

- name: Test pod connectivity to internet
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl exec -n calico-test pingtest -- ping -c 4 8.8.8.8
  register: ping_test
  become: yes
  changed_when: false
  ignore_errors: true
  when: pod_ready is succeeded

- name: Display ping test results
  debug:
    var: ping_test.stdout_lines
  when: ping_test is defined

- name: Cleanup test resources
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    kubectl delete namespace calico-test
  register: cleanup
  become: yes
  changed_when: false
  ignore_errors: true 