---
# Jenkins Server Playbook
# This playbook applies the base_server role for system configuration and jenkins_podman role to deploy Jenkins

- name: Deploy Jenkins Server
  hosts: jenkins-server
  become: yes
  gather_facts: yes
  
  roles:
    - role: ../ansible/roles/base_server
    - role: ../ansible/roles/virtfs_mount
    - role: ../ansible/roles/jenkins_podman

  post_tasks:
    - name: Report completion
      debug:
        msg: "Jenkins server configuration completed successfully on {{ inventory_hostname }}"
    
    - name: Show Jenkins access information
      debug:
        msg: "Jenkins is available at http://{{ inventory_hostname }}:{{ jenkins_http_port }}" 