---
# Kubernetes Node Playbook
# This playbook applies the base_server role for system configuration and kubernetes_node role to join Kubernetes cluster

- name: Deploy Kubernetes Node
  hosts: kubernetes_nodes
  become: yes
  gather_facts: yes
  
  vars:
    join_command: "{{ lookup('file', '/home/gabriel/git_projects/homelab-ai/kubernetes-cluster/join_command.txt') }}"
  
  roles:
    - role: ../ansible/roles/base_server
    - role: kubernetes_node

  pre_tasks:
    - name: Check if server is reachable
      wait_for_connection:
        timeout: 10
      ignore_errors: yes
      register: connection_status
    
    - name: Fail if server is unreachable
      fail:
        msg: "Could not connect to {{ inventory_hostname }}. Please check connectivity."
      when: connection_status.failed

  post_tasks:
    - name: Report completion
      debug:
        msg: "Kubernetes node configuration completed successfully on {{ inventory_hostname }}" 