---
# Playbook to reset the Kubernetes cluster
- name: Reset Kubernetes on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Reset Kubernetes with kubeadm
      command: kubeadm reset -f
      ignore_errors: yes

    - name: Stop and disable kubelet
      systemd:
        name: kubelet
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove Kubernetes directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /var/lib/etcd
        - /etc/cni/net.d
        - /var/lib/cni
        - /var/run/calico
        - $HOME/.kube
      ignore_errors: yes

    - name: Remove CNI interfaces
      command: ip link delete flannel.1
      ignore_errors: yes

    - name: Remove CNI interfaces
      command: ip link delete cni0
      ignore_errors: yes

    - name: Remove CNI interfaces
      command: ip link delete calico
      ignore_errors: yes

    - name: Flush iptables rules
      command: "{{ item }}"
      with_items:
        - iptables -F
        - iptables -t nat -F
        - iptables -t mangle -F
        - iptables -X
      ignore_errors: yes

    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted
      ignore_errors: yes 