---
# Base Server Playbook
# This playbook applies the base_server role to configure essential packages and security settings

- name: Configure base servers
  hosts: all
  become: yes
  gather_facts: yes
  
  roles:
    - role: base_server
      tags: 
        - base
        - system
        - security

  pre_tasks:
    - name: Check if server is reachable
      wait_for_connection:
        timeout: 10
      ignore_errors: yes
      register: connection_status
    
    - name: Fail if server is unreachable
      fail:
        msg: "Could not connect to {{ inventory_hostname }}. Please check connectivity."
      when: connection_status.failed

  post_tasks:
    - name: Report completion
      debug:
        msg: "Base server configuration completed successfully on {{ inventory_hostname }}" 