---
# Inventory file for server management

all:
  children:
    # Most servers should be in the base_servers group
    base_servers:
      hosts:
      children:
        jenkins_servers:
          hosts:
            jenkins_server:
              ansible_host: jenkins-server.i.psilva.org
              ansible_user: ubuntu
              jenkins_http_port: 8080
              jenkins_agent_port: 50000
              server_timezone: "UTC"
            jenkins_worker1:
              ansible_host: jenkins-worker1.i.psilva.org
              ansible_user: ubuntu
              jenkins_http_port: 8080
              jenkins_agent_port: 50000
              server_timezone: "UTC"          
        kubernetes_master_nodes:
          hosts:
            kmaster1:
              ansible_host: kmaster1.i.psilva.org
              ansible_user: ubuntu
              apiserver_advertise_address: "{{ ansible_default_ipv4.address }}"
              server_timezone: "UTC"
        kubernetes_worker_nodes:
          hosts:
            knode1:
              ansible_host: knode1.i.psilva.org
              ansible_user: ubuntu
              server_timezone: "UTC"
