---
# Main tasks file for kubernetes_worker role

- name: Add Kubernetes signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.32/deb/Release.key
    dest: /tmp/kubernetes-apt-key.gpg
  become: true
  when: ansible_os_family == "Debian"

- name: Dearmor key
  ansible.builtin.shell: cat /tmp/kubernetes-apt-key.gpg | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  become: true
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: ansible_os_family == "Debian"

- name: Create kubernetes repository directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true
  when: ansible_os_family == "Debian"

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.32/deb/ /"
    state: present
    filename: kubernetes
  become: true
  when: ansible_os_family == "Debian"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Install containerd
  ansible.builtin.apt:
    name: containerd
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Create containerd directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: "0755"
  become: true

- name: Configure containerd
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  become: true
  args:
    creates: /etc/containerd/config.toml

- name: Edit containerd configuration to use systemd cgroup driver
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    regexp: "^\\s+SystemdCgroup = false"
    line: "            SystemdCgroup = true"
  become: true
  notify: restart containerd

- name: Install Kubernetes packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - lsof
  when: ansible_os_family == "Debian"

- name: Hold Kubernetes packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
    - containerd
  become: true
  when: ansible_os_family == "Debian"

- name: Disable swap
  ansible.builtin.command: swapoff -a
  become: true

- name: Remove swap from fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: ".*swap.*"
    state: absent
  become: true

- name: Enable kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter
  become: true

- name: Add kernel modules to /etc/modules-load.d/
  ansible.builtin.copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/kubernetes.conf
    mode: "0644"
  become: true

- name: Configure sysctl for Kubernetes
  ansible.builtin.copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    mode: "0644"
  become: true

- name: Apply sysctl changes immediately
  ansible.builtin.command: sysctl --system
  become: true
  register: sysrestart
  changed_when: sysrestart.rc != 0
