---
# Base Server Playbook
# This playbook applies the base_server role to configure essential packages and security settings

- name: Configure base servers
  hosts: base_servers
  become: yes
  gather_facts: yes
  
  roles:
    - role: ../../roles/base_server

  post_tasks:
    - name: Report completion
      debug:
        msg: "Base server configuration completed successfully on {{ inventory_hostname }}" 