---
# Handlers for kubernetes_node role

- name: restart containerd
  service:
    name: containerd
    state: restarted
  become: yes

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
  become: yes 